[package]
name = "Remora"
version = "1.0.0"
authors = ["Remora Team"]
license = "Apache-2.0"

[addresses]
remora = "0xCAFE"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
remora = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]